cc_test(
    name = "test_http",
    srcs = [
        "test_http.c",
    ],
    deps = [
        "//endpoint:https",
        "//endpoint/connectivity:conn_http",
        "//tests:logger_lib",
        "//tests:test_define",
    ],
)
