version: "3.8"

services:
  app:
    build: .
    image: tangle-accelerator
    container_name: tangle-accelerator
    command: "./bazel-bin/accelerator/accelerator --config=ta_config.yaml"
    ports:
      - "8000:8000"
    depends_on:
      - redis_server

  redis_server:
    image: redis:6.0.8
    container_name: redis
    ports:
      - "6379:6379"
