package(default_visibility = ["//visibility:public"])

cc_library(
    name = "cache",
    srcs = ["cache.c"],
    hdrs = ["cache.h"],
    deps = [
        "//:ta_config",
        "//third_party:hiredis",
    ],
)
