#!/bin/bash

root=$(git rev-parse --show-toplevel)
banned="([^f]gets\()|(sprintf\()|(strcpy\()"
status=0
for file in $(git diff --staged --name-only | grep -E "\.(c|cc|cpp|h|hh|hpp)\$")
do
  filepath="${root}/${file}"
  output=$(grep -nrE "${banned}" "${filepath}")
  if [ ! -z "${output}" ]; then
      echo "Dangerous function detected in ${filepath}"
      echo "${output}"
      status=1
  fi
done
exit $status
