cc_test(
    name = "test_text_serializer",
    srcs = [
        "test_text_serializer.c",
    ],
    deps = [
        "//endpoint:cipher",
        "//endpoint:text_serializer",
        "//tests:logger_lib",
        "//tests:test_define",
    ],
)

cc_test(
    name = "test_cipher",
    srcs = [
        "test_cipher.c",
    ],
    deps = [
        "//endpoint:cipher",
        "//tests:logger_lib",
        "//tests:test_define",
    ],
)
