cc_library(
    name = "http",
    srcs = ["http.c"],
    hdrs = ["http.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//accelerator/core:apis",
        "//accelerator/core:proxy_apis",
        "@libmicrohttpd",
    ],
)
