cc_library(
    name = "common",
    srcs = [
        "common.c",
    ],
    hdrs = [
        "common.h",
    ],
    visibility = ["//connectivity:__subpackages__"],
    deps = [
        "//common",
        "@cJSON",
    ],
)
