cc_binary(
    name = "monitor",
    srcs = [
        "monitor.c",
    ],
    deps = [
        "//common:ta_errors",
        "//endpoint/OBDComp:obd_pid",
        "//endpoint/OBDComp/can-bus:can-utils",
    ],
)
