package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mode",
    srcs = ["mode.c"],
    hdrs = ["mode.h"],
    deps = [
        "@entangled//common/trinary:tryte_ascii",
        "@entangled//mam/api",
    ],
)
