cc_test(
    name = "test_http",
    srcs = [
        "test_http.c",
    ],
    deps = [
        "//tests:test_define",
        "//utils/connectivity:conn_http",
    ],
)

cc_test(
    name = "test_endpoint_core",
    srcs = [
        "test_endpoint_core.c",
    ],
    deps = [
        "//common:ta_errors",
        "//common:ta_logger",
        "//endpoint:endpoint_core",
        "//tests:test_define",
    ],
)
